import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth
import json
import boto3

service_key = json.loads(boto3.client('ssm').get_parameter(Name='/glof/dev/firebase_service_key'))

cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(cred)

decoded_token = auth.verify_id_token("eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5NGNmYTAxOTgyMDNlMjgwN2Q4MzRkYmE2MjBlZjczZjI4ZTRlMmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZ2V0bGFuZG9uZm9vdCIsImF1ZCI6ImdldGxhbmRvbmZvb3QiLCJhdXRoX3RpbWUiOjE2MzYzNzcxNDcsInVzZXJfaWQiOiJFN0pxRE5CY0dPZllld3V2SjJKdTh1b2hQa3AyIiwic3ViIjoiRTdKcUROQmNHT2ZZZXd1dkoySnU4dW9oUGtwMiIsImlhdCI6MTYzNjM3NzE1OSwiZXhwIjoxNjM2MzgwNzU5LCJlbWFpbCI6InByaWRla2tAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInByaWRla2tAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.jLduWfvcCpAbuxlPh6jOv9Y-9YaA7S-qHd1fvOn15hlw7uHJbXQHzwTmhgpSwrrMKT5ypFpSppM3zMDDmRq6OyJhcrCr-_l53jfwAMgcyLORo_u38hmJCqwuTM4sZM7O3WhIn5gQLzMCDYC0oieBOHmKxjShaBxBn33biGcsdnp53MdVsIDUggEwNQV1TveshsdSXKyNe95JCQBKld-0IQHXKa-7KL8BNxOJXZDD2Czb_guPyKqnWyEpHwzbxdXWk6qNYR_5Q2iYFPe-RwEICRrhz-aW0mxAx5pOLcGiayEKM1zWiWBy5Mfi-QPvAW51xkHcKiUt7CvR7tdaymEbcw")

if __name__ == "__main__":
    print("test")